# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19igPXC-Rmjh0_CXYXOg9YzcW3WUK_EMo
"""

print('hallo world')